spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}764524d3d87d724fba178c9fdf1ff80e97b662342d90cbeae39bb6c36980a0a9'

token:
  expiration_time: 86400005
  secret: dfmlejkfjdjdddf1241524ghdas

gateway:
  ip: 127.0.0.1
